# Generated by Django 5.1.7 on 2025-03-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_user_type_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('outlet', 'Outlet')], default='outlet', max_length=10),
        ),
    ]
