# Generated by Django 5.1.7 on 2025-06-19 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_serial_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfccard',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='nfccard',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='nfccard',
            name='name',
        ),
        migrations.AddField(
            model_name='nfccard',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Linked customer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.customer'),
        ),
    ]
