# Generated by Django 5.1.7 on 2025-03-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nfccard_balance_nfccard_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfccard',
            name='secure_key',
            field=models.CharField(blank=True, help_text='Secure 16-character alphanumeric key for transactions', max_length=16, unique=True),
        ),
    ]
