# Generated by Django 5.1.7 on 2025-03-30 23:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_nfccard_secure_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_identifier', models.CharField(help_text='Card ID at the time of transaction', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10)),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Card balance before transaction', max_digits=10)),
                ('new_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Card balance after transaction', max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('pending', 'Pending'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('card', models.ForeignKey(blank=True, help_text='NFC card used for the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.nfccard')),
                ('outlet', models.ForeignKey(blank=True, help_text='Outlet where the transaction occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.outlet')),
                ('user', models.ForeignKey(blank=True, help_text='User who processed the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
