# Generated by Django 5.1.7 on 2025-04-13 17:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the event', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the event')),
                ('start_date', models.DateField(help_text='Start date of the event')),
                ('end_date', models.DateField(help_text='End date of the event')),
                ('start_time', models.TimeField(help_text='Start time of the event')),
                ('end_time', models.TimeField(help_text='End time of the event')),
                ('location', models.CharField(help_text='Location of the event', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the event is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='nfclog',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event associated with the log', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.event'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event associated with the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.event'),
        ),
        migrations.CreateModel(
            name='EventStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_transactions', models.IntegerField(default=0, help_text='Total number of transactions during the event')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue during the event', max_digits=10)),
                ('cards_issued', models.IntegerField(default=0, help_text='Number of cards issued during the event')),
                ('top_ups', models.IntegerField(default=0, help_text='Number of top-ups during the event')),
                ('payments', models.IntegerField(default=0, help_text='Number of payments during the event')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_outlets', to='core.event')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_events', to='core.outlet')),
            ],
            options={
                'unique_together': {('event', 'outlet')},
            },
        ),
    ]
