# Generated by Django 5.1.7 on 2025-04-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event_nfclog_event_transaction_event_eventstatistics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventstatistics',
            name='cards_issued',
        ),
        migrations.RemoveField(
            model_name='eventstatistics',
            name='payments',
        ),
        migrations.RemoveField(
            model_name='eventstatistics',
            name='top_ups',
        ),
    ]
