# Generated by Django 5.1.7 on 2025-04-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_analytics_alter_profile_user_type_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCollectionAnalytics',
            fields=[
            ],
            options={
                'verbose_name': 'Collection Analytics',
                'verbose_name_plural': 'Collection Analytics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.transaction',),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('nfc', 'NFC')], default='cash', help_text='Method used for payment (Cash or UPI)', max_length=10),
        ),
    ]
