# Generated by Django 5.1.7 on 2025-04-26 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_paymentcollectionanalytics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Volunteer',
            new_name='TopupVolunteer',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('outlet', 'Outlet'), ('topup_volunteer', 'Topup Volunteers')], default='outlet', max_length=15),
        ),
    ]
